Set-StrictMode -Version Latest

$script:WmsRoot = Split-Path -Parent $PSScriptRoot

function Write-Step([string]$Message) {
    Write-Host "`n==> $Message" -ForegroundColor Cyan
}

function Write-Ok([string]$Message) {
    Write-Host "[OK] $Message" -ForegroundColor Green
}

function Assert-Docker {
    if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
        throw "Docker was not found. Install Docker Desktop first: https://www.docker.com/products/docker-desktop/"
    }

    & docker info *> $null
    if ($LASTEXITCODE -ne 0) {
        throw "Docker is installed but the engine is not running. Start Docker Desktop and try again."
    }

    & docker compose version *> $null
    if ($LASTEXITCODE -ne 0) {
        throw "Docker Compose v2 is required. Update Docker Desktop and try again."
    }
}

function Get-ComposePath {
    return Join-Path $script:WmsRoot "deploy/docker-compose.yaml"
}

function Invoke-WmsCompose {
    param([Parameter(ValueFromRemainingArguments = $true)][string[]]$ComposeArgs)

    $composePath = Get-ComposePath
    & docker compose -f $composePath @ComposeArgs
    if ($LASTEXITCODE -ne 0) {
        throw "docker compose failed with exit code $LASTEXITCODE"
    }
}

function New-RandomHex {
    param([int]$ByteCount = 32)

    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try {
        $bytes = New-Object byte[] $ByteCount
        $rng.GetBytes($bytes)
        return ($bytes | ForEach-Object { $_.ToString("x2") }) -join ""
    }
    finally {
        $rng.Dispose()
    }
}

function Read-DotEnv {
    param([string]$Path)

    $map = [ordered]@{}
    if (-not (Test-Path -LiteralPath $Path)) {
        return $map
    }

    foreach ($rawLine in [System.IO.File]::ReadAllLines($Path)) {
        $line = $rawLine.Trim()
        if ($line.Length -eq 0 -or $line.StartsWith("#")) {
            continue
        }
        $separator = $line.IndexOf("=")
        if ($separator -lt 1) {
            continue
        }
        $key = $line.Substring(0, $separator).Trim()
        $value = $line.Substring($separator + 1).Trim()
        if (($value.StartsWith('"') -and $value.EndsWith('"')) -or
            ($value.StartsWith("'") -and $value.EndsWith("'"))) {
            $value = $value.Substring(1, $value.Length - 2)
        }
        $map[$key] = $value
    }
    return $map
}

function Save-DotEnv {
    param(
        [string]$Path,
        [System.Collections.IDictionary]$Values
    )

    $preferredKeys = @(
        "MYSQL_ROOT_PASSWORD",
        "MYSQL_DATABASE",
        "JWT_SECRET",
        "WMS_SERVER_NODE",
        "WMS_API_PORT",
        "WMS_WEB_PORT"
    )

    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add("# Generated by start.ps1. Keep this file private.")
    foreach ($key in $preferredKeys) {
        if ($Values.Contains($key)) {
            $lines.Add("$key=$($Values[$key])")
        }
    }
    foreach ($key in $Values.Keys) {
        if ($preferredKeys -notcontains $key) {
            $lines.Add("$key=$($Values[$key])")
        }
    }

    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($Path, ($lines -join [Environment]::NewLine) + [Environment]::NewLine, $utf8NoBom)
}

function Test-PlaceholderSecret {
    param([string]$Value)

    if ([string]::IsNullOrWhiteSpace($Value)) {
        return $true
    }
    return $Value -match "(?i)change|placeholder|your-|dev-secret"
}
