Set-StrictMode -Version Latest

$script:WmsRoot = Split-Path -Parent $PSScriptRoot

function Write-Step([string]$Message) {
    Write-Host "`n==> $Message" -ForegroundColor Cyan
}

function Write-Ok([string]$Message) {
    Write-Host "[OK] $Message" -ForegroundColor Green
}

function Get-DockerDesktopPath {
    # Common Docker Desktop install locations on Windows.
    # String interpolation is used (instead of Join-Path) so unset
    # env vars like ProgramFiles(x86) on 32-bit Windows don't throw.
    $candidates = @(
        "$env:ProgramFiles\Docker\Docker\Docker Desktop.exe",
        "${env:ProgramFiles(x86)}\Docker\Docker\Docker Desktop.exe",
        "$env:LOCALAPPDATA\Programs\Docker\Docker\Docker Desktop.exe"
    )
    foreach ($path in $candidates) {
        if ($path -and (Test-Path -LiteralPath $path)) {
            return $path
        }
    }
    return $null
}

function Wait-DockerEngine {
    param([int]$TimeoutSeconds = 120)

    $deadline = (Get-Date).AddSeconds($TimeoutSeconds)
    while ((Get-Date) -lt $deadline) {
        & docker info *> $null
        if ($LASTEXITCODE -eq 0) {
            return $true
        }
        Start-Sleep -Seconds 3
    }
    return $false
}

function Assert-Docker {
    if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
        throw "Docker was not found. Install Docker Desktop first: https://www.docker.com/products/docker-desktop/"
    }

    & docker info *> $null
    if ($LASTEXITCODE -ne 0) {
        Write-Step "Docker engine is not running. Starting Docker Desktop..."
        $dockerExe = Get-DockerDesktopPath
        if (-not $dockerExe) {
            throw "Docker Desktop is not running and its executable was not found. Start Docker Desktop manually and try again."
        }
        Start-Process -FilePath $dockerExe
        $ready = Wait-DockerEngine -TimeoutSeconds 120
        if (-not $ready) {
            throw "Docker Desktop did not become ready within 2 minutes. Open Docker Desktop manually and try again."
        }
        Write-Ok "Docker Desktop is now running"
    }

    & docker compose version *> $null
    if ($LASTEXITCODE -ne 0) {
        throw "Docker Compose v2 is required. Update Docker Desktop and try again."
    }
}

function Get-ComposePath {
    return Join-Path $script:WmsRoot "deploy/docker-compose.yaml"
}

function Invoke-WmsCompose {
    param([Parameter(ValueFromRemainingArguments = $true)][string[]]$ComposeArgs)

    $composePath = Get-ComposePath
    # Explicitly point --env-file at the project root .env so variable
    # interpolation works regardless of where the compose file lives.
    $envPath = Join-Path $script:WmsRoot ".env"
    $envFileArgs = @()
    if (Test-Path -LiteralPath $envPath) {
        $envFileArgs = @("--env-file", $envPath)
    }
    & docker compose -f $composePath @envFileArgs @ComposeArgs
    if ($LASTEXITCODE -ne 0) {
        throw "docker compose failed with exit code $LASTEXITCODE"
    }
}

function New-RandomHex {
    param([int]$ByteCount = 32)

    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try {
        $bytes = New-Object byte[] $ByteCount
        $rng.GetBytes($bytes)
        return ($bytes | ForEach-Object { $_.ToString("x2") }) -join ""
    }
    finally {
        $rng.Dispose()
    }
}

function Read-DotEnv {
    param([string]$Path)

    $map = [ordered]@{}
    if (-not (Test-Path -LiteralPath $Path)) {
        return $map
    }

    foreach ($rawLine in [System.IO.File]::ReadAllLines($Path)) {
        $line = $rawLine.Trim()
        if ($line.Length -eq 0 -or $line.StartsWith("#")) {
            continue
        }
        $separator = $line.IndexOf("=")
        if ($separator -lt 1) {
            continue
        }
        $key = $line.Substring(0, $separator).Trim()
        $value = $line.Substring($separator + 1).Trim()
        if (($value.StartsWith('"') -and $value.EndsWith('"')) -or
            ($value.StartsWith("'") -and $value.EndsWith("'"))) {
            $value = $value.Substring(1, $value.Length - 2)
        }
        $map[$key] = $value
    }
    return $map
}

function Save-DotEnv {
    param(
        [string]$Path,
        [System.Collections.IDictionary]$Values
    )

    $preferredKeys = @(
        "MYSQL_ROOT_PASSWORD",
        "MYSQL_DATABASE",
        "JWT_SECRET",
        "WMS_INTEGRATION_API_KEY",
        "WMS_SERVER_NODE",
        "WMS_API_BIND",
        "WMS_API_PORT",
        "WMS_WEB_PORT",
        "WMS_GRAFANA_PORT",
        "WMS_GRAFANA_ADMIN_USER",
        "WMS_GRAFANA_ADMIN_PASSWORD",
        "WMS_DEMO_ENABLED",
        "WMS_DEMO_INSTANCES",
        "WMS_DEMO_PASSWORD",
        "WMS_DEMO_SESSION_TTL_SECONDS"
    )

    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add("# Generated by start.ps1. Keep this file private.")
    foreach ($key in $preferredKeys) {
        if ($Values.Contains($key)) {
            $lines.Add("$key=$($Values[$key])")
        }
    }
    foreach ($key in $Values.Keys) {
        if ($preferredKeys -notcontains $key) {
            $lines.Add("$key=$($Values[$key])")
        }
    }

    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($Path, ($lines -join [Environment]::NewLine) + [Environment]::NewLine, $utf8NoBom)
}

function Test-PlaceholderSecret {
    param([string]$Value)

    if ([string]::IsNullOrWhiteSpace($Value)) {
        return $true
    }
    return $Value -match "(?i)change|placeholder|your-|dev-secret"
}
